version: 2.0
jobs:
  build:
    docker:
      - image: gradle:jdk11
    steps:
      - checkout
      - run:
          name: The First Step
          command:
            ci/build-app.sh
            echo 'This is the delivery pipeline.'
      - store_artifacts:
          path: /code/artifact
          destination: prefix
      - run:
          name: test step
          command:
            ci/unit-test-app.sh
      - store_test_results:
          path: app/build/test-results
      